// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr6KjswwYBfYva2ZD0MtJ1NzsSn3CM5GI',
    appId: '1:318898926018:web:eac1652ff23a09dd35e65b',
    messagingSenderId: '318898926018',
    projectId: 'to-do-app-13de4',
    authDomain: 'to-do-app-13de4.firebaseapp.com',
    storageBucket: 'to-do-app-13de4.firebasestorage.app',
    measurementId: 'G-GFRVJTJ9XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL8pByeVPoCYJYfU_8OLmL9yVR3blr35M',
    appId: '1:318898926018:android:55a5b718e14b10eb35e65b',
    messagingSenderId: '318898926018',
    projectId: 'to-do-app-13de4',
    storageBucket: 'to-do-app-13de4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTQ2Uupzxcg3DgXlpGtFvslURmvDCV1II',
    appId: '1:318898926018:ios:415550d8bccb6e4835e65b',
    messagingSenderId: '318898926018',
    projectId: 'to-do-app-13de4',
    storageBucket: 'to-do-app-13de4.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTQ2Uupzxcg3DgXlpGtFvslURmvDCV1II',
    appId: '1:318898926018:ios:415550d8bccb6e4835e65b',
    messagingSenderId: '318898926018',
    projectId: 'to-do-app-13de4',
    storageBucket: 'to-do-app-13de4.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr6KjswwYBfYva2ZD0MtJ1NzsSn3CM5GI',
    appId: '1:318898926018:web:a267eae5b5d8c3df35e65b',
    messagingSenderId: '318898926018',
    projectId: 'to-do-app-13de4',
    authDomain: 'to-do-app-13de4.firebaseapp.com',
    storageBucket: 'to-do-app-13de4.firebasestorage.app',
    measurementId: 'G-0WZRWLF8FM',
  );
}
